blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/stitch-digital/laravel-simpro-api/discussions/new?category=q-a
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/stitch-digital/laravel-simpro-api/issues/new?template=feature_request.yml
    about: Share ideas for new features
  - name: Report a security issue
    url: https://github.com/stitch-digital/laravel-simpro-api/security/policy
    about: Learn how to notify us for sensitive bugs
