name: "Update Changelog"

on:
  release:
    types: [released]

permissions:
  contents: write
  pull-requests: write  # Ensure the workflow can create pull requests

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
          branch: auto-update-changelog # Commit to a new branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: auto-update-changelog  # Use the branch from the previous step
          base: main                     # Target the main branch
          title: 'Auto-update CHANGELOG'
          body: 'This pull request was created automatically to update the CHANGELOG file.'
          commit-message: 'Update CHANGELOG'
